name: markdown_browser

description: A package to simplify browsing markdown files. 

version: 0.0.1

homepage: https://www.cloudonlanapps.com

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_custom_tabs: ^1.2.1
  flutter_math_fork: ^0.7.1
  flutter_riverpod: ^2.4.4
  http: ^1.1.0
  markdown: ^7.1.1
  markdown_widget: ^2.3.1
  material_design_icons_flutter: ^7.0.7296
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
